### ISSUE TITLE
Upgrade to postgresql-client 13

### ISSUE THREAD

**Issue by fahrenheit9** [bitnami/bitnami-docker-phppgadmin#3]
**Description**

Upgrade postgresql-client to version 13. Exporting a database from Phppgadmin fails because of pg_dump version being not compatible with version of Psql.

`pg_dump: server version: 13.3 (Debian 13.3-1.pgdg100+1); pg_dump version: 11.12
pg_dump: aborting because of server version mismatch`

**Steps to reproduce the issue:**

1. Run a container with postgres:13
2. Run a container with bitnami/phppgadmin:7.13.0
3. Login to phppgadmin
4. Export database

**Describe the results you received:**

White page or empty sql dump

**Describe the results you expected:**

The content of the export

**Additional information you deem important (e.g. issue happens only occasionally):**

Output log after investigating the issue from withing the container:
`pg_dump: server version: 13.3 (Debian 13.3-1.pgdg100+1); pg_dump version: 11.12
pg_dump: aborting because of server version mismatch`

**Version**

- Output of `docker version`: 

```
Docker version 20.10.7
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Happens on Mac os, Ubuntu 20

**Comment by javsalgar** [comment]
Hi,

Thanks for letting us know. As you said, we may need to change the postgresql-client binary we're using in the container. I will open a task for this.

**Comment by fahrenheit9** [comment]
Hi, 
thanks for you reply.

I rebuilt your image locally with the psql client version 13.3.0-0 (already hosted on Bitnami servers) and it works like a charm.

Have a nice day.

**Comment by javsalgar** [comment]
Thanks for letting us know!

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-phppgadmin#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
